name: scrcpy_flutter_windows
description: A Flutter project for scrcpy on Windows.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.12.0
  path_provider: ^2.0.11
  file_picker: ^4.6.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size